/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : FreeRunning.h
**     Project     : PEX_C_Project
**     Processor   : MK20DX128VLH5
**     Component   : FreeCntr
**     Version     : Component 01.118, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-04-28, 19:50, # CodeGen: 23
**     Abstract    :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings    :
**         Timer name                  : PIT_CVAL0 (32-bit)
**         Compare name                : PIT_LDVAL0
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 0 Hz
**           Period
**             microseconds            : ---
**             milliseconds            : ---
**             seconds                 : 400
**             seconds (real)          : 400.0
**             Hz                      : ---
**             kHz                     : ---
**             MHz                     : ---
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 0
**
**         Initialization:
**              Timer                  : Enabled
**
**         Timer registers
**              Counter                : PIT_CVAL0 [0x40037104]
**              Mode                   : PIT_MCR   [0x40037000]
**              Run                    : PIT_TCTRL0 [0x40037108]
**              Compare                : PIT_LDVAL0 [0x40037100]
**
**         User handling procedure     : not specified
**     Contents    :
**         Reset           - byte FreeRunning_Reset(void);
**         GetCounterValue - byte FreeRunning_GetCounterValue(FreeRunning_TTimerValue *Value);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FreeRunning.h
** @version 01.00
** @brief
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
*/         
/*!
**  @addtogroup FreeRunning_module FreeRunning module documentation
**  @{
*/         

#ifndef __FreeRunning_H
#define __FreeRunning_H

/* MODULE FreeRunning. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "FreeCntrLdd1.h"

#include "Cpu.h"


#ifndef __BWUserType_FreeRunning_TTimerValue
#define __BWUserType_FreeRunning_TTimerValue
  typedef dword FreeRunning_TTimerValue ; /* Counter or compare value, width depends on timer width, 8, 16, 32 or 64 bits. */
#endif

#ifdef FreeCntrLdd1_PERIOD_TICKS
#define FreeRunning_PERIOD_VALUE FreeCntrLdd1_PERIOD_TICKS /* Initial period/offset value in ticks of the timer. It is available only if the component is enabled in high speed mode. */
#define FreeRunning_PERIOD_VALUE_HIGH FreeRunning_PERIOD_VALUE /* Period value in ticks of the timer in high speed mode. It is available only if the component is enabled in high speed mode. */
#endif
#define FreeRunning_PRESCALER_VALUE 0x01UL /* Initial prescaler value of the timer. It is available only if the component is enabled in high speed mode. */
#define FreeRunning_PRESCALER_VALUE_HIGH 0x01UL /* Prescaler value of the timer in high speed mode. It is available only if the component is enabled in high speed mode. */
#define FreeRunning_COUNTER_INPUT_CLOCK_HZ FreeCntrLdd1_CNT_INP_FREQ_U_0 /* Initial counter input clock frequency [Hz] (integer number). It is available only if the component is enabled in high speed mode. */
#define FreeRunning_COUNTER_INPUT_CLOCK_HZ_HIGH FreeCntrLdd1_CNT_INP_FREQ_U_0_CFG_0 /* Counter input clock frequency in high speed mode [Hz] (integer number). It is available only if the component is enabled in high speed mode. */
#if FreeCntrLdd1_COUNTER_DIR == 0
#define FreeRunning_UP_COUNTER 1       /* This constant is defined if the counter counts upwards, e.g. from 0 to maximal value. */
#endif
#if FreeCntrLdd1_COUNTER_DIR == 1
#define FreeRunning_DOWN_COUNTER 1     /* This constant is defined if the counter counts down, e.g. from maximal value to 0. */
#endif
#define FreeRunning_RESET_ON_COMPARE 1 /* This constant is defined if Reset counter on compare property is selected. */


/*
** ===================================================================
**     Method      :  FreeRunning_Reset (component FreeCntr)
*/
/*!
**     @brief
**         This method resets the timer-counter (sets to zero for
**         up-counting HW or to appropriate value for down-counting HW).
**         The method is available only if the counter register can be
**         set by software and the counter is not shared.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
#define FreeRunning_Reset() (FreeCntrLdd1_ResetCounter(FreeCntrLdd1_DeviceData))

/*
** ===================================================================
**     Method      :  FreeRunning_GetCounterValue (component FreeCntr)
*/
/*!
**     @brief
**         This method returns a content of the counter.
**     @param
**         Value           - Pointer to returned value.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte FreeRunning_GetCounterValue(FreeRunning_TTimerValue *Value);

/* END FreeRunning. */

#endif 
/* ifndef __FreeRunning_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
